from ursina import *
import hashlib

def hash_category(category):
    """Hashes a category name to 3D coordinates (limited to 6x6x6 grid)."""
    hash_object = hashlib.sha256(category.encode())
    hex_digest = hash_object.hexdigest()
    x = int(hex_digest[0:2], 16) % 10  # Modulo for creation of  3d  memory-coordinate
    y = int(hex_digest[2:4], 16) % 10  # Modulo for y-coordinate
    z = int(hex_digest[4:6], 16) % 10  # Modulo for z-coordinate
    return x, y, z

def create_category_node(category):
    """Creates a 3D node for a category."""
    x, y, z = hash_category(category)
    node = Entity(model='cube', color=color.blue, scale=0.25, position=(x, y, z), name=category, collider='box')
    node.opacity = 0.5  # Make the box transparent
    return node

def create_no_category_node():
    """Creates a 3D node for categories with no assignment."""
    # Place the "Category_None" node at a unique position
    node = Entity(model='cube', color=color.gray, scale=0.25, position=(3, 3, 3), name='Category_None', collider='box')
    node.opacity = 0.5  # Make the box transparent
    return node

def create_empty_node(x, y, z):
    """Creates a 3D node for empty grid spaces."""
    node = Entity(model='cube', color=color.brown, scale=0.25, position=(x, y, z), collider='box')
    node.opacity = 0.7  # Make the box transparent
    return node

def add_connection(start_node, end_node, direction, strength):
    """Creates an arrow connection between two category nodes."""
    # Use a pre-existing model or create your own arrow model
    arrow = Entity(model='arrow', color=color.red, scale=(0.1, 0.1, 0.3)) # Use the 'arrow' model
    arrow.position = start_node.position + (end_node.position - start_node.position) * 0.5
    arrow.look_at(end_node, axis='forward')  # Align the arrow with the direction
    return arrow

# Create the main Ursina application
app = Ursina(win_size=(864, 1536), background=color.black)  # Set background to black

# Example categories
categories = [
    "Events", "Actions", "Concepts", "People", "Places",
    "Emotions", "Relationships", "Objects", "Time", "Space",
    "Sounds", "Colors", "Tastes", "Smells", "Textures",
    "Body Parts", "Animals", "Plants", "Materials", "Tools",
    "Buildings", "Transportation", "Food", "Clothing", "Technology",
    "Arts", "Sports", "Games", "Education", "Health",
    "Nature", "Weather", "Geography", "History", "Culture",
    "Politics", "Economics", "Science", "Technology", "Society",
    "Language", "Communication", "Logic", "Mathematics", "Philosophy",
    "Religion", "Spirituality", "Mythology", "Literature", "Music",
    "Art", "Design", "Fashion", "Entertainment", "Media",
    "Law", "Justice", "Crime", "War", "Peace",
    "Love", "Hate", "Fear", "Joy", "Sadness",
    "Family", "Friendship", "Community", "Society", "World",

    # Expanding upon the original categories
    "Personal Events", "Social Events", "Natural Events", "Historical Events", "Cultural Events",
    "Physical Actions", "Mental Actions", "Social Actions", "Work Actions", "Travel Actions",
    "Abstract Concepts", "Social Concepts", "Philosophical Concepts", "Scientific Concepts", "Technological Concepts",
    "Family Members", "Friends", "Professionals", "Community Members", "Historical Figures",
    "Cities", "Countries", "Continents", "Landforms", "Bodies of Water",
    "Happiness", "Anger", "Surprise", "Disgust", "Shame",
    "Romantic Relationships", "Family Relationships", "Friendships", "Professional Relationships",
    "Social Relationships",
    "Furniture", "Electronics", "Vehicles", "Clothing", "Jewelry",
    "Past", "Present", "Future", "Seasons", "Time Periods",
    "Direction", "Distance", "Location", "Dimensions", "Coordinates",
    "Music Genres", "Musical Instruments", "Music Theory", "Composers", "Musicians",
    "Painting", "Sculpture", "Photography", "Film", "Architecture",
    "Sports Teams", "Sports Rules", "Sports Equipment", "Athletes", "Coaches",
    "Board Games", "Card Games", "Video Games", "Puzzles", "Role-Playing Games",
    "Schools", "Universities", "Libraries", "Museums", "Research Institutions",
    "Medicine", "Nutrition", "Fitness", "Mental Health", "Wellness",
    "Forests", "Deserts", "Oceans", "Mountains", "Rivers",
    "Weather Patterns", "Climate Change", "Natural Disasters", "Environmental Issues", "Sustainability",
    "Ancient History", "Medieval History", "Modern History", "Contemporary History", "World History",
    "Culinary Traditions", "Art Forms", "Festivals", "Belief Systems", "Social Customs",
    "Political Systems", "Government", "Laws", "Politics", "Ideologies",
    "Economy", "Business", "Finance", "Trade", "Globalization",
    "Biology", "Chemistry", "Physics", "Astronomy", "Mathematics",
    "Software", "Hardware", "Artificial Intelligence", "Robotics", "Nanotechnology",
    "Social Issues", "Inequality", "Poverty", "Racism", "Gender Equality",
    "Grammar", "Vocabulary", "Phonology", "Morphology", "Syntax",
    "Communication Skills", "Public Speaking", "Writing", "Negotiation", "Conflict Resolution",
    "Reasoning", "Deduction", "Induction", "Critical Thinking", "Problem Solving",
    "Numbers", "Equations", "Geometry", "Algebra", "Calculus",
    "Ethics", "Morality", "Values", "Meaning", "Purpose",
    "Theism", "Atheism", "Agnosticism", "Spirituality", "Mysticism",
    "Myths", "Legends", "Folklore", "Fairy Tales", "Epic Poems",
    "Novels", "Short Stories", "Poetry", "Drama", "Nonfiction",
    "Classical Music", "Jazz", "Rock", "Pop", "Electronic Music",
    "Painting Styles", "Sculpture Styles", "Architectural Styles", "Design Trends", "Fashion Trends",
    "Movies", "TV Shows", "Music Videos", "Video Games", "Theater",
    "Legal Systems", "Crimes", "Punishments", "Justice", "Law Enforcement",
    "Warfare", "Peacekeeping", "Conflict Resolution", "Human Rights", "International Relations",
    "Friendship", "Love", "Marriage", "Family", "Community",
    "Happiness", "Sadness", "Anger", "Fear", "Anxiety",
    "Culture", "Society", "Community", "Identity", "Values",
    "Global Issues", "Climate Change", "Poverty", "Disease", "Conflict",

    # Expanding on specific areas
    "Types of Events", "Event Planning", "Event Management",
    "Types of Actions", "Action Verbs", "Action Phrases",
    "Types of Concepts", "Conceptual Thinking", "Abstract Reasoning",
    "Types of People", "Personality Traits", "Human Behavior",
    "Types of Places", "Geography", "Urban Planning",
    "Types of Emotions", "Emotional Intelligence", "Emotional Regulation",
    "Types of Relationships", "Relationship Dynamics", "Communication Skills",
    "Types of Objects", "Material Science", "Design",
    "Types of Time", "Chronology", "Time Management",
    "Types of Space", "Dimensions", "Coordinate Systems",
    "Types of Sounds", "Acoustics", "Music Theory",
    "Types of Colors", "Color Theory", "Color Psychology",
    "Types of Tastes", "Culinary Arts", "Food Science",
    "Types of Smells", "Aromatherapy", "Perfume",
    "Types of Textures", "Material Science", "Sensory Perception",
    "Types of Body Parts", "Anatomy", "Physiology",
    "Types of Animals", "Zoology", "Animal Behavior",
    "Types of Plants", "Botany", "Plant Ecology",
    "Types of Materials", "Material Science", "Engineering",
    "Types of Tools", "Technology", "Engineering",
    "Types of Buildings", "Architecture", "Urban Design",
    "Types of Transportation", "Automotive Engineering", "Aerospace Engineering",
    "Types of Food", "Culinary Arts", "Nutrition",
    "Types of Clothing", "Fashion Design", "Textile Industry",
    "Types of Technology", "Computer Science", "Engineering",
    "Types of Arts", "Art History", "Art Theory",
    "Types of Sports", "Sports Science", "Exercise Physiology",
    "Types of Games", "Game Design", "Game Theory",
    "Types of Education", "Educational Psychology", "Curriculum Development",
    "Types of Health", "Medicine", "Public Health",
    "Types of Nature", "Ecology", "Environmental Science",
    "Types of Weather", "Meteorology", "Climate Science",
    "Types of Geography", "Cartography", "Geographic Information Systems",
    "Types of History", "Historiography", "Historical Research",
    "Types of Culture", "Anthropology", "Sociology",
    "Types of Politics", "Political Science", "International Relations",
    "Types of Economics", "Microeconomics", "Macroeconomics",
    "Types of Science", "Scientific Method", "Research",
    "Types of Technology", "Computer Science", "Engineering",
    "Types of Society", "Sociology", "Social Psychology",
    "Types of Language", "Linguistics", "Language Acquisition",
    "Types of Communication", "Communication Theory", "Interpersonal Communication",
    "Types of Logic", "Formal Logic", "Informal Logic",
    "Types of Mathematics", "Algebra", "Geometry", "Calculus",
    "Types of Philosophy", "Ethics", "Metaphysics", "Epistemology",
    "Types of Religion", "Theology", "Religious Studies",
    "Types of Spirituality", "Mysticism", "Meditation",
    "Types of Mythology", "Mythology", "Folklore",
    "Types of Literature", "Literary Theory", "Critical Analysis",
    "Types of Music", "Music Theory", "Music History",
    "Types of Art", "Art History", "Art Criticism",
    "Types of Design", "Design Thinking", "User Experience Design",
    "Types of Fashion", "Fashion History", "Fashion Design",
    "Types of Entertainment", "Media Studies", "Entertainment Industry",
    "Types of Media", "Journalism", "Public Relations",
    "Types of Law", "Legal Studies", "Jurisprudence",
    "Types of Justice", "Criminal Justice", "Social Justice",
    "Types of Crime", "Criminology", "Forensic Science",
    "Types of War", "Military History", "International Relations",
    "Types of Peace", "Peace Studies", "Conflict Resolution",
    "Types of Love", "Romantic Love", "Platonic Love",
    "Types of Hate", "Prejudice", "Discrimination",
    "Types of Fear", "Phobias", "Anxiety Disorders",
    "Types of Joy", "Happiness", "Well-being",
    "Types of Sadness", "Grief", "Depression",
    "Types of Family", "Family Dynamics", "Parenting",
    "Types of Friendship", "Friendship Dynamics", "Social Support",
    "Types of Community", "Community Development", "Social Networks",
    "Types of Society", "Sociology", "Social Stratification",
    "Types of World", "Global Issues", "International Relations",

    # More specific examples
    "Sports Leagues", "Sports Championships", "Sports Records",
    "Types of Music", "Music Genres", "Musical Instruments",
    "Types of Art", "Art Styles", "Art Movements",
    "Types of Food", "Cuisine", "Recipes",
    "Types of Technology", "Gadgets", "Software",
    "Types of Buildings", "Architecture Styles", "City Planning",
    "Types of Vehicles", "Cars", "Airplanes", "Trains",
    "Types of Clothing", "Fashion Trends", "Textile Production",
    "Types of Animals", "Wildlife", "Domesticated Animals",
    "Types of Plants", "Flowers", "Trees", "Vegetables",
    "Types of Weather", "Climate Change", "Natural Disasters",
    "Types of History", "Ancient History", "Medieval History", "Modern History",
    "Types of Culture", "Traditions", "Customs", "Festivals",
    "Types of Politics", "Political Systems", "Ideologies",
    "Types of Economics", "Markets", "Trade", "Finance",
    "Types of Science", "Physics", "Chemistry", "Biology",
    "Types of Technology", "Computers", "Internet", "Artificial Intelligence",
    "Types of Society", "Social Class", "Culture", "Values",
    "Types of Language", "Grammar", "Vocabulary", "Phonology",
    "Types of Communication", "Verbal Communication", "Nonverbal Communication",
    "Types of Logic", "Deductive Reasoning", "Inductive Reasoning",
    "Types of Mathematics", "Algebra", "Geometry", "Calculus",
    "Types of Philosophy", "Ethics", "Metaphysics", "Epistemology",
    "Types of Religion", "Christianity", "Islam", "Buddhism",
    "Types of Spirituality", "Meditation", "Yoga", "Mysticism",
    "Types of Mythology", "Greek Mythology", "Roman Mythology", "Norse Mythology",
    "Types of Literature", "Poetry", "Fiction", "Nonfiction",
    "Types of Music", "Classical Music", "Jazz", "Rock", "Pop",
    "Types of Art", "Painting", "Sculpture", "Photography", "Film",
    "Types of Design", "Graphic Design", "Web Design", "Industrial Design",
    "Types of Fashion", "Streetwear", "High Fashion", "Couture",
    "Types of Entertainment", "Movies", "TV Shows", "Video Games",
    "Types of Media", "News", "Social Media", "Advertising",
    "Types of Law", "Criminal Law", "Civil Law", "International Law",
    "Types of Justice", "Criminal Justice", "Social Justice",
    "Types of Crime", "Violent Crime", "Property Crime", "White-Collar Crime",
    "Types of War", "World War II", "Cold War", "Civil Wars",
    "Types of Peace", "Peace Treaties", "Peace Movements", "Nonviolent Resistance",
    "Types of Love", "Romantic Love", "Platonic Love", "Familial Love",
    "Types of Hate", "Racism", "Sexism", "Homophobia",
    "Types of Fear", "Phobias", "Anxiety", "Panic Attacks",
    "Types of Joy", "Happiness", "Gratitude", "Contentment",
    "Types of Sadness", "Grief", "Depression", "Loneliness",
    "Types of Family", "Nuclear Family", "Extended Family", "Blended Family",
    "Types of Friendship", "Casual Friendships", "Close Friendships", "Best Friends",
    "Types of Community", "Rural Communities", "Urban Communities", "Online Communities",
    "Types of Society", "Capitalist Societies", "Socialist Societies", "Communist Societies",
    "Types of World", "Global Issues", "Climate Change", "Poverty", "Disease",
    "Types of Jobs", "Professions", "Careers", "Industries", "Occupations",
    "Types of Education", "Formal Education", "Informal Education", "Higher Education",
    "Types of Health", "Physical Health", "Mental Health", "Social Health",
    "Types of Nature", "Ecosystems", "Biodiversity", "Conservation",
    "Types of Weather", "Temperature", "Precipitation", "Wind",
    "Types of Geography", "Landforms", "Bodies of Water", "Climate Zones",
    "Types of History", "Ancient History", "Medieval History", "Modern History",
    "Types of Culture", "Art", "Music", "Literature", "Food",
    "Types of Politics", "Democracy", "Republic", "Monarchy",
    "Types of Economics", "Capitalism", "Socialism", "Communism",
    "Types of Science", "Physics", "Chemistry", "Biology", "Astronomy",
    "Types of Technology", "Computers", "Internet", "Artificial Intelligence",
    "Types of Society", "Social Class", "Culture", "Values",
    "Types of Language", "Grammar", "Vocabulary", "Phonology",
    "Types of Communication", "Verbal Communication", "Nonverbal Communication",
    "Types of Logic", "Deductive Reasoning", "Inductive Reasoning",
    "Types of Mathematics", "Algebra", "Geometry", "Calculus",
    "Types of Philosophy", "Ethics", "Metaphysics", "Epistemology",
    "Types of Religion", "Christianity", "Islam", "Buddhism",
    "Types of Spirituality", "Meditation", "Yoga", "Mysticism",
    "Types of Mythology", "Greek Mythology", "Roman Mythology", "Norse Mythology",
    "Types of Literature", "Poetry", "Fiction", "Nonfiction",
    "Types of Music", "Classical Music", "Jazz", "Rock", "Pop",
    "Types of Art", "Painting", "Sculpture", "Photography", "Film",
    "Types of Design", "Graphic Design", "Web Design", "Industrial Design",
    "Types of Fashion", "Streetwear", "High Fashion", "Couture",
    "Types of Entertainment", "Movies", "TV Shows", "Video Games",
    "Types of Media", "News", "Social Media", "Advertising",
    "Types of Law", "Criminal Law", "Civil Law", "International Law",
    "Types of Justice", "Criminal Justice", "Social Justice",
    "Types of Crime", "Violent Crime", "Property Crime", "White-Collar Crime",
    "Types of War", "World War II", "Cold War", "Civil Wars",
    "Types of Peace", "Peace Treaties", "Peace Movements", "Nonviolent Resistance",
    "Types of Love", "Romantic Love", "Platonic Love", "Familial Love",
    "Types of Hate", "Racism", "Sexism", "Homophobia",
    "Types of Fear", "Phobias", "Anxiety", "Panic Attacks",
    "Types of Joy", "Happiness", "Gratitude", "Contentment",
    "Types of Sadness", "Grief", "Depression", "Loneliness",
    "Types of Family", "Nuclear Family", "Extended Family", "Blended Family",
    "Types of Friendship", "Casual Friendships", "Close Friendships", "Best Friends",
    "Types of Community", "Rural Communities", "Urban Communities", "Online Communities",
    "Types of Society", "Capitalist Societies", "Socialist Societies", "Communist Societies",
    "Types of World", "Global Issues", "Climate Change", "Poverty", "Disease",
    "Types of Travel", "Adventure Travel", "Luxury Travel", "Backpacking",
    "Types of Cuisine", "Italian Cuisine", "French Cuisine", "Indian Cuisine",
    "Types of Art", "Abstract Art", "Surrealism", "Impressionism",
    "Types of Music", "Classical Music", "Jazz", "Rock", "Pop",
    "Types of Sports", "Team Sports", "Individual Sports", "Extreme Sports",
    "Types of Technology", "Computers", "Mobile Devices", "Artificial Intelligence",
    "Types of Science", "Biology", "Chemistry", "Physics", "Astronomy",
    "Types of History", "Ancient History", "Medieval History", "Modern History",
    "Types of Culture", "Art", "Music", "Literature", "Food", "Religion",
    "Types of Politics", "Democracy", "Republic", "Monarchy",
    "Types of Economics", "Capitalism", "Socialism", "Communism",
    "Types of Society", "Social Class", "Culture", "Values",
    "Types of Language", "Grammar", "Vocabulary", "Phonology",
    "Types of Communication", "Verbal Communication", "Nonverbal Communication",
    "Types of Logic", "Deductive Reasoning", "Inductive Reasoning",
    "Types of Mathematics", "Algebra", "Geometry", "Calculus",
    "Types of Philosophy", "Ethics", "Metaphysics", "Epistemology",
    "Types of Religion", "Christianity", "Islam", "Buddhism",
    "Types of Spirituality", "Meditation", "Yoga", "Mysticism",
    "Types of Mythology", "Greek Mythology", "Roman Mythology", "Norse Mythology",
    "Types of Literature", "Poetry", "Fiction", "Nonfiction",
    "Types of Music", "Classical Music", "Jazz", "Rock", "Pop",
    "Types of Art", "Painting", "Sculpture", "Photography", "Film",
    "Types of Design", "Graphic Design", "Web Design", "Industrial Design",
    "Types of Fashion", "Streetwear", "High Fashion", "Couture",
    "Types of Entertainment", "Movies", "TV Shows", "Video Games",
    "Types of Media", "News", "Social Media", "Advertising",
    "Types of Law", "Criminal Law", "Civil Law", "International Law",
    "Types of Justice", "Criminal Justice", "Social Justice",
    "Types of Crime", "Violent Crime", "Property Crime", "White-Collar Crime",
    "Types of War", "World War II", "Cold War", "Civil Wars",
    "Types of Peace", "Peace Treaties", "Peace Movements", "Nonviolent Resistance",
    "Types of Love", "Romantic Love", "Platonic Love", "Familial Love",
    "Types of Hate", "Racism", "Sexism", "Homophobia",
    "Types of Fear", "Phobias", "Anxiety", "Panic Attacks",
    "Types of Joy", "Happiness", "Gratitude", "Contentment",
    "Types of Sadness", "Grief", "Depression", "Loneliness",
    "Types of Family", "Nuclear Family", "Extended Family", "Blended Family",
    "Types of Friendship", "Casual Friendships", "Close Friendships", "Best Friends",
    "Types of Community", "Rural Communities", "Urban Communities", "Online Communities",
    "Types of Society", "Capitalist Societies", "Socialist Societies", "Communist Societies",
    "Types of World", "Global Issues", "Climate Change", "Poverty", "Disease",
    "Types of Jobs", "Professions", "Careers", "Industries", "Occupations",
    "Types of Education", "Formal Education", "Informal Education", "Higher Education",
    "Types of Health", "Physical Health", "Mental Health", "Social Health",
    "Types of Nature", "Ecosystems", "Biodiversity", "Conservation",
    "Types of Weather", "Temperature", "Precipitation", "Wind",
    "Types of Geography", "Landforms", "Bodies of Water", "Climate Zones",
    "Types of History", "Ancient History", "Medieval History", "Modern History",
    "Types of Culture", "Art", "Music", "Literature", "Food", "Religion",
    "Types of Politics", "Democracy", "Republic", "Monarchy",
    "Types of Economics", "Capitalism", "Socialism", "Communism",
    "Types of Society", "Social Class", "Culture", "Values",
    "Types of Language", "Grammar", "Vocabulary", "Phonology",
    "Types of Communication", "Verbal Communication", "Nonverbal Communication",
    "Types of Logic", "Deductive Reasoning", "Inductive Reasoning",
    "Types of Mathematics", "Algebra", "Geometry", "Calculus",
    "Types of Philosophy", "Ethics", "Metaphysics", "Epistemology",
    "Types of Religion", "Christianity", "Islam", "Buddhism",
    "Types of Spirituality", "Meditation", "Yoga", "Mysticism",
    "Types of Mythology", "Greek Mythology", "Roman Mythology", "Norse Mythology",
    "Types of Literature", "Poetry", "Fiction", "Nonfiction",
    "Types of Music", "Classical Music", "Jazz", "Rock", "Pop",
    "Types of Art", "Painting", "Sculpture", "Photography", "Film",
    "Types of Design", "Graphic Design", "Web Design", "Industrial Design",
    "Types of Fashion", "Streetwear", "High Fashion", "Couture",
    "Types of Entertainment", "Movies", "TV Shows", "Video Games",
    "Types of Media", "News", "Social Media", "Advertising",
    "Types of Law", "Criminal Law", "Civil Law", "International Law",
    "Types of Justice", "Criminal Justice", "Social Justice",
    "Types of Crime", "Violent Crime", "Property Crime", "White-Collar Crime",
    "Types of War", "World War II", "Cold War", "Civil Wars",
    "Types of Peace", "Peace Treaties", "Peace Movements", "Nonviolent Resistance",
    "Types of Love", "Romantic Love", "Platonic Love", "Familial Love",
    "Types of Hate", "Racism", "Sexism", "Homophobia",
    "Types of Fear", "Phobias", "Anxiety", "Panic Attacks",
    "Types of Joy", "Happiness", "Gratitude", "Contentment",
    "Types of Sadness", "Grief", "Depression", "Loneliness",
    "Types of Family", "Nuclear Family", "Extended Family", "Blended Family",
    "Types of Friendship", "Casual Friendships", "Close Friendships", "Best Friends",
    "Types of Community", "Rural Communities", "Urban Communities", "Online Communities",
    "Types of Society", "Capitalist Societies", "Socialist Societies", "Communist Societies",
    "Types of World", "Global Issues", "Climate Change", "Poverty", "Disease",
    "Types of Jobs", "Professions", "Careers", "Industries", "Occupations",
    "Types of Education", "Formal Education", "Informal Education", "Higher Education",
    "Types of Health", "Physical Health", "Mental Health", "Social Health",
    "Types of Nature", "Ecosystems", "Biodiversity", "Conservation",
    "Types of Weather", "Temperature", "Precipitation", "Wind",
    "Types of Geography", "Landforms", "Bodies of Water", "Climate Zones",
    "Types of History", "Ancient History", "Medieval History", "Modern History",
    "Types of Culture", "Art", "Music", "Literature", "Food", "Religion",
    "Types of Politics", "Democracy", "Republic", "Monarchy",
    "Types of Economics", "Capitalism", "Socialism", "Communism",
    "Types of Society", "Social Class", "Culture", "Values",
    "Types of Language", "Grammar", "Vocabulary", "Phonology",
    "Types of Communication", "Verbal Communication", "Nonverbal Communication",
    "Types of Logic", "Deductive Reasoning", "Inductive Reasoning",
    "Types of Mathematics", "Algebra", "Geometry", "Calculus",
    "Types of Philosophy", "Ethics", "Metaphysics", "Epistemology",
    "Types of Religion", "Christianity", "Islam", "Buddhism",
    "Types of Spirituality", "Meditation", "Yoga", "Mysticism",
    "Types of Mythology", "Greek Mythology", "Roman Mythology", "Norse Mythology",
    "Types of Literature", "Poetry", "Fiction", "Nonfiction",
    "Types of Music", "Classical Music", "Jazz", "Rock", "Pop",
    "Types of Art", "Painting", "Sculpture", "Photography", "Film",
    "Types of Design", "Graphic Design", "Web Design", "Industrial Design",
    "Types of Fashion", "Streetwear", "High Fashion", "Couture",
    "Types of Entertainment", "Movies", "TV Shows", "Video Games",
    "Types of Media", "News", "Social Media", "Advertising",
    "Types of Law", "Criminal Law", "Civil Law", "International Law",
    "Types of Justice", "Criminal Justice", "Social Justice",
    "Types of Crime", "Violent Crime", "Property Crime", "White-Collar Crime",
    "Types of War", "World War II", "Cold War", "Civil Wars",
    "Types of Peace", "Peace Treaties", "Peace Movements", "Nonviolent Resistance",
    "Types of Love", "Romantic Love", "Platonic Love", "Familial Love",
    "Types of Hate", "Racism", "Sexism", "Homophobia",
    "Types of Fear", "Phobias", "Anxiety", "Panic Attacks",
    "Types of Joy", "Happiness", "Gratitude", "Contentment",
    "Types of Sadness", "Grief", "Depression", "Loneliness",
    "Types of Family", "Nuclear Family", "Extended Family", "Blended Family",
    "Types of Friendship", "Casual Friendships", "Close Friendships", "Best Friends",
    "Types of Community", "Rural Communities", "Urban Communities", "Online Communities",
    "Types of Society", "Capitalist Societies", "Socialist Societies", "Communist Societies",
    "Types of World", "Global Issues", "Climate Change", "Poverty", "Disease",
    "Types of Jobs", "Professions", "Careers", "Industries", "Occupations",
    "Types of Education", "Formal Education", "Informal Education", "Higher Education",
    "Types of Health", "Physical Health", "Mental Health", "Social Health",
    "Types of Nature", "Ecosystems", "Biodiversity", "Conservation",
    "Types of Weather", "Temperature", "Precipitation", "Wind",
    "Types of Geography", "Landforms", "Bodies of Water", "Climate Zones",
    "Types of History", "Ancient History", "Medieval History", "Modern History",
    "Types of Culture", "Art", "Music", "Literature", "Food", "Religion",
    "Types of Politics", "Democracy", "Republic", "Monarchy",
    "Types of Economics", "Capitalism", "Socialism", "Communism",
    "Types of Society", "Social Class", "Culture", "Values",
    "Types of Language", "Grammar", "Vocabulary", "Phonology",
    "Types of Communication", "Verbal Communication", "Nonverbal Communication",
    "Types of Logic", "Deductive Reasoning", "Inductive Reasoning",
    "Types of Mathematics", "Algebra", "Geometry", "Calculus",
    "Types of Philosophy", "Ethics", "Metaphysics", "Epistemology",
    "Types of Religion", "Christianity", "Islam", "Buddhism",
    "Types of Spirituality", "Meditation", "Yoga", "Mysticism",
    "Types of Mythology", "Greek Mythology", "Roman Mythology", "Norse Mythology",
    "Types of Literature", "Poetry", "Fiction", "Nonfiction",
    "Types of Music", "Classical Music", "Jazz", "Rock", "Pop",
    "Types of Art", "Painting", "Sculpture", "Photography", "Film",
    "Types of Design", "Graphic Design", "Web Design", "Industrial Design",
    "Types of Fashion", "Streetwear", "High Fashion", "Couture",
    "Types of Entertainment", "Movies", "TV Shows", "Video Games",
    "Types of Media", "News", "Social Media", "Advertising",
    "Types of Law", "Criminal Law", "Civil Law", "International Law",
    "Types of Justice", "Criminal Justice", "Social Justice",
    "Types of Crime", "Violent Crime", "Property Crime", "White-Collar Crime",
    "Types of War", "World War II", "Cold War", "Civil Wars",
    "Types of Peace", "Peace Treaties", "Peace Movements", "Nonviolent Resistance",
    "Types of Love", "Romantic Love", "Platonic Love", "Familial Love",
    "Types of Hate", "Racism", "Sexism", "Homophobia",
    "Types of Fear", "Phobias", "Anxiety", "Panic Attacks",
    "Types of Joy", "Happiness", "Gratitude", "Contentment",
    "Types of Sadness", "Grief", "Depression", "Loneliness",
    "Types of Family", "Nuclear Family", "Extended Family", "Blended Family",
    "Types of Friendship", "Casual Friendships", "Close Friendships", "Best Friends",
    "Types of Community", "Rural Communities", "Urban Communities", "Online Communities",
    "Types of Society", "Capitalist Societies", "Socialist Societies", "Communist Societies",
    "Types of World", "Global Issues", "Climate Change", "Poverty", "Disease",
    "Types of Jobs", "Professions", "Careers", "Industries", "Occupations",
    "Types of Education", "Formal Education", "Informal Education", "Higher Education",
    "Types of Health", "Physical Health", "Mental Health", "Social Health",
    "Types of Nature", "Ecosystems", "Biodiversity", "Conservation",
    "Types of Weather", "Temperature", "Precipitation", "Wind",
    "Types of Geography", "Landforms", "Bodies of Water", "Climate Zones",
    "Types of History", "Ancient History", "Medieval History", "Modern History",
    "Types of Culture", "Art", "Music", "Literature", "Food", "Religion",
    "Types of Politics", "Democracy", "Republic", "Monarchy",
    "Types of Economics", "Capitalism", "Socialism", "Communism",
    "Types of Society", "Social Class", "Culture", "Values",
    "Types of Language", "Grammar", "Vocabulary", "Phonology",
    "Types of Communication", "Verbal Communication", "Nonverbal Communication",
    "Types of Logic", "Deductive Reasoning", "Inductive Reasoning",
    "Types of Mathematics", "Algebra", "Geometry", "Calculus",
    "Types of Philosophy", "Ethics", "Metaphysics", "Epistemology",
    "Types of Religion", "Christianity", "Islam", "Buddhism",
    "Types of Spirituality", "Meditation", "Yoga", "Mysticism",
    "Types of Mythology", "Greek Mythology", "Roman Mythology", "Norse Mythology",
    "Types of Literature", "Poetry", "Fiction", "Nonfiction",
    "Types of Music", "Classical Music", "Jazz", "Rock", "Pop",
    "Types of Art", "Painting", "Sculpture", "Photography", "Film",
    "Types of Design", "Graphic Design", "Web Design", "Industrial Design",
    "Types of Fashion", "Streetwear", "High Fashion", "Couture",
    "Types of Entertainment", "Movies", "TV Shows", "Video Games",
    "Types of Media", "News", "Social Media", "Advertising",
    "Types of Law", "Criminal Law", "Civil Law", "International Law",
    "Types of Justice", "Criminal Justice", "Social Justice",
    "Types of Crime", "Violent Crime", "Property Crime", "White-Collar Crime",
    "Types of War", "World War II", "Cold War", "Civil Wars",
    "Types of Peace", "Peace Treaties", "Peace Movements", "Nonviolent Resistance",
    "Types of Love", "Romantic Love", "Platonic Love", "Familial Love",
    "Types of Hate", "Racism", "Sexism", "Homophobia",
    "Types of Fear", "Phobias", "Anxiety", "Panic Attacks",
    "Types of Joy", "Happiness", "Gratitude", "Contentment",
    "Types of Sadness", "Grief", "Depression", "Loneliness",
    "Types of Family", "Nuclear Family", "Extended Family", "Blended Family",
    "Types of Friendship", "Casual Friendships", "Close Friendships", "Best Friends",
    "Types of Community", "Rural Communities", "Urban Communities", "Online Communities",
    "Types of Society", "Capitalist Societies", "Socialist Societies", "Communist Societies",
    "Types of World", "Global Issues", "Climate Change", "Poverty", "Disease",
    "Types of Jobs", "Professions", "Careers", "Industries", "Occupations",
    "Types of Education", "Formal Education", "Informal Education", "Higher Education",
    "Types of Health", "Physical Health", "Mental Health", "Social Health",
    "Types of Nature", "Ecosystems", "Biodiversity", "Conservation",
    "Types of Weather", "Temperature", "Precipitation", "Wind",
    "Types of Geography", "Landforms", "Bodies of Water", "Climate Zones",
    "Types of History", "Ancient History", "Medieval History", "Modern History",
    "Types of Culture", "Art", "Music", "Literature", "Food", "Religion",
    "Types of Politics", "Democracy", "Republic", "Monarchy",
    "Types of Economics", "Capitalism", "Socialism", "Communism",
    "Types of Society", "Social Class", "Culture", "Values",
    "Types of Language", "Grammar", "Vocabulary", "Phonology",
    "Types of Communication", "Verbal Communication", "Nonverbal Communication",
    "Types of Logic", "Deductive Reasoning", "Inductive Reasoning",
    "Types of Mathematics", "Algebra", "Geometry", "Calculus",
    "Types of Philosophy", "Ethics", "Metaphysics", "Epistemology",
    "Types of Religion", "Christianity", "Islam", "Buddhism",
    "Types of Spirituality", "Meditation", "Yoga", "Mysticism",
    "Types of Mythology", "Greek Mythology", "Roman Mythology", "Norse Mythology",
    "Types of Literature", "Poetry", "Fiction", "Nonfiction",
    "Types of Music", "Classical Music", "Jazz", "Rock", "Pop",
    "Types of Art", "Painting", "Sculpture", "Photography", "Film",
    "Types of Design", "Graphic Design", "Web Design", "Industrial Design",
    "Types of Fashion", "Streetwear", "High Fashion", "Couture",
    "Types of Entertainment", "Movies", "TV Shows", "Video Games",
    "Types of Media", "News", "Social Media", "Advertising"]

# Create a dictionary to store category nodes
category_nodes = {}
folder_nodes = {}  # Create a dictionary to store folders

# Create 3D nodes for each category and organize into folders
for category in categories:
    node = create_category_node(category)
    category_nodes[category] = node  # Store the node for easy access
    folder_name = "Folder_" + category
    if folder_name not in folder_nodes:
        folder_nodes[folder_name] = Entity(name=folder_name)  # Create a folder entity if it doesn't exist
    node.parent = folder_nodes[folder_name]  # Set parent to the corresponding folder

# Create nodes for categories with no assignment
no_category_node = create_no_category_node()
folder_nodes['Folder_Category_None'] = Entity(name='Folder_Category_None')  # Create the folder
no_category_node.parent = folder_nodes['Folder_Category_None']  # Assign the node to the folder

# Create nodes to fill the remaining grid spaces
for x in range(6):
    for y in range(6):
        for z in range(6):
            position = (x, y, z)
            if position not in [node.position for node in category_nodes.values()]:
                empty_node = create_empty_node(x, y, z)

# Example connections (customize these)
connections = [
    ("Events", "Actions"),
    ("Actions", "Events"),
    ("Concepts", "Science"),
    ("Science", "Technology"),
]

# Create arrows for connections
for start_category, end_category in connections:
    start_node = category_nodes[start_category]
    end_node = category_nodes[end_category]
    arrow = add_connection(start_node, end_node, "Forward", 0.8)  # Assuming connections are bi-directional

# Add a camera
camera.position = (0, 0, -10)  # Move the camera back a bit

# Enable free flight
EditorCamera()

# Lighting
directional_light = DirectionalLight(color=color.white, strength=0.8)
ambient_light = AmbientLight(color=color.white, strength=0.3) # Set ambient light strength to 0.3
spotlight = SpotLight(parent=camera, color=color.white, range=20) # add a spotlight

# Run the application
app.run()